[phases.setup]
nixPkgs = ['php', 'phpPackages.composer', 'nodejs', 'nginx', 'phpExtensions.pdo_mysql', 'phpExtensions.gd', 'phpExtensions.zip', 'phpExtensions.curl', 'phpExtensions.mbstring', 'phpExtensions.xml', 'phpExtensions.bcmath', 'phpExtensions.fileinfo']

[variables]
BROADCAST_CONNECTION = "reverb"
REVERB_APP_KEY = "local"
REVERB_APP_SECRET = "local"
REVERB_APP_ID = "local"
REVERB_HOST = "localhost"
REVERB_PORT = "443"
REVERB_SCHEME = "https"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
SESSION_DRIVER = "file"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"

[phases.install]
cmds = [
    "mkdir -p /app/bootstrap/cache",
    "mkdir -p /app/storage/app",
    "mkdir -p /app/storage/framework/cache",
    "mkdir -p /app/storage/framework/sessions", 
    "mkdir -p /app/storage/framework/views",
    "mkdir -p /app/storage/logs",
    "mkdir -p /app/storage/frontend",
    "chmod -R 775 /app/bootstrap/cache",
    "chmod -R 775 /app/storage",
    "composer install --ignore-platform-reqs",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
